title: UCSC WordPress Theme
description: The official theme for UC Santa Cruz WordPress sites.
url: https://ucsc.github.io
lang: en-US
github_username: ucsc

# Publishing
permalink: pretty
exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock

# Frontmatter defaults
defaults:
  - scope:
      path: ""
    values:
      image: /assets/images/opengraph_image.png

# Theme
remote_theme: just-the-docs/just-the-docs
aux_links:
  "UCSC on GitHub":
    - https://github.com/ucsc/
logo: assets/images/uc-santa-cruz.svg
color_scheme: ucsc

# GitHub edit link
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_branch: main
gh_edit_repository: https://github.com/ucsc/theme-ucsc
gh_edit_source: docs
gh_edit_view_mode: tree

# Plug-ins
optional_front_matter:
  remove_originals: true
